# Generated by Django 2.0.4 on 2018-04-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='language',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='code',
            name='room',
            field=models.CharField(default='language', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='code',
            name='source',
            field=models.TextField(blank=True),
        ),
    ]
