# Generated by Django 2.0.4 on 2018-04-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_auto_20180420_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='room',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
