# Generated by Django 2.0.4 on 2018-04-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_auto_20180420_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='language',
            field=models.CharField(blank=True, default='python', max_length=12),
        ),
    ]
